// ===================================
// Global State Management
// ===================================
let currentModel = 'gpt4';
let currentFramework = 'selenium';
let testHistory = [];

// ===================================
// Page Navigation
// ===================================
function showPage(pageName) {
    // Hide all pages
    const pages = ['landing-page', 'login-page', 'generator-page', 'comparison-page', 'history-page'];
    pages.forEach(page => {
        document.getElementById(page).style.display = 'none';
    });

    // Show selected page
    const pageMap = {
        'home': 'landing-page',
        'login': 'login-page',
        'generator': 'generator-page',
        'comparison': 'comparison-page',
        'history': 'history-page'
    };

    const pageToShow = pageMap[pageName];
    if (pageToShow) {
        document.getElementById(pageToShow).style.display = 'block';
    }

    // Scroll to top
    window.scrollTo({ top: 0, behavior: 'smooth' });
}

// ===================================
// Model Selection
// ===================================
function selectModel(element, model) {
    // Remove active class from all model cards
    document.querySelectorAll('.model-card').forEach(card => {
        card.classList.remove('active');
        const icon = card.querySelector('.bi');
        icon.className = 'bi bi-circle';
        icon.style.color = 'var(--border-color)';
    });

    // Add active to selected card
    element.classList.add('active');
    const icon = element.querySelector('.bi');
    icon.className = 'bi bi-check-circle-fill text-success';

    // Update current model
    currentModel = model;
    console.log('Selected model:', model);
}

// ===================================
// Test Generation - Main Generator
// ===================================
function generateTest() {
    const instructions = document.getElementById('test-instructions').value;
    
    if (!instructions.trim()) {
        alert('Ве молиме внесете инструкции за тестот!');
        return;
    }

    const output = document.getElementById('code-output');
    
    // Show loading state
    output.innerHTML = `
        <div class="text-center">
            <i class="bi bi-hourglass-split"></i>
            <p class="mt-2">Генерирање<span class="loading-dots"><span>.</span><span>.</span><span>.</span></span></p>
        </div>
    `;

    // Simulate API call (2 seconds delay)
    setTimeout(() => {
        const code = generateMockCode(instructions, currentModel, currentFramework);
        output.innerHTML = `<pre><code class="text-light">${escapeHtml(code)}</code></pre>`;
        
        // Add to history
        addToHistory(instructions, currentModel, currentFramework, code);
    }, 2000);
}

// ===================================
// Mock Code Generation
// ===================================
function generateMockCode(instructions, model, framework) {
    // This is a mock function - in production, this would call the backend API
    
    if (framework === 'selenium') {
        return `from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

def test_generated():
    """
    Test generated by ${model.toUpperCase()}
    Instructions: ${instructions}
    """
    # Иницијализирај driver
    driver = webdriver.Chrome()
    
    try:
        # Тест код генериран со AI
        driver.get("https://example.com")
        
        # Пример акции базирани на инструкциите
        element = WebDriverWait(driver, 10).until(
            EC.presence_of_element_located((By.ID, "test-element"))
        )
        element.click()
        
        print("✅ Тестот помина успешно!")
        
    except Exception as e:
        print(f"❌ Грешка: {e}")
        
    finally:
        driver.quit()

if __name__ == "__main__":
    test_generated()`;
    } else {
        return `const { chromium } = require('playwright');

async function testGenerated() {
    /**
     * Test generated by ${model.toUpperCase()}
     * Instructions: ${instructions}
     */
    const browser = await chromium.launch();
    const context = await browser.newContext();
    const page = await context.newPage();
    
    try {
        // Тест код генериран со AI
        await page.goto('https://example.com');
        
        // Пример акции базирани на инструкциите
        await page.click('#test-element');
        
        console.log('✅ Тестот помина успешно!');
        
    } catch (error) {
        console.error('❌ Грешка:', error);
    } finally {
        await browser.close();
    }
}

testGenerated();`;
    }
}

// ===================================
// Comparison Generation
// ===================================
function generateComparison() {
    const instructions = document.getElementById('comparison-instructions').value;
    
    if (!instructions.trim()) {
        alert('Ве молиме внесете инструкции!');
        return;
    }

    const models = ['gpt', 'claude', 'gemini'];
    
    models.forEach(model => {
        const outputElement = document.getElementById(`${model}-output`);
        const timeElement = document.getElementById(`${model}-time`);
        
        // Show loading
        outputElement.innerHTML = `
            <div class="text-center">
                <i class="bi bi-hourglass-split"></i>
                <p class="mt-2">Генерирање<span class="loading-dots"><span>.</span><span>.</span><span>.</span></span></p>
            </div>
        `;
        
        // Simulate API calls with different delays
        const delay = Math.random() * 2000 + 1500; // 1.5-3.5 seconds
        
        setTimeout(() => {
            const code = generateMockCode(instructions, model, 'selenium');
            outputElement.innerHTML = `<pre><code class="text-light" style="font-size: 0.75rem;">${escapeHtml(code)}</code></pre>`;
            timeElement.textContent = `${(delay / 1000).toFixed(1)}s`;
        }, delay);
    });
}

// ===================================
// Copy Functionality
// ===================================
function copyCode() {
    const codeElement = document.querySelector('#code-output pre code');
    if (!codeElement) return;
    
    const code = codeElement.textContent;
    
    navigator.clipboard.writeText(code).then(() => {
        // Show success feedback
        const btn = event.target.closest('.copy-btn');
        const originalHTML = btn.innerHTML;
        btn.innerHTML = '<i class="bi bi-check-circle"></i> Копирано!';
        
        setTimeout(() => {
            btn.innerHTML = originalHTML;
        }, 2000);
    }).catch(err => {
        console.error('Failed to copy:', err);
        alert('Грешка при копирање!');
    });
}

function copyComparisonCode(model) {
    const codeElement = document.querySelector(`#${model}-output pre code`);
    if (!codeElement) return;
    
    const code = codeElement.textContent;
    
    navigator.clipboard.writeText(code).then(() => {
        alert('Кодот е копиран!');
    }).catch(err => {
        console.error('Failed to copy:', err);
        alert('Грешка при копирање!');
    });
}

// ===================================
// History Management
// ===================================
function addToHistory(instructions, model, framework, code) {
    const now = new Date();
    const timestamp = now.toLocaleString('mk-MK', {
        day: '2-digit',
        month: '2-digit',
        year: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
    });
    
    const historyItem = {
        id: Date.now(),
        title: generateTestTitle(instructions),
        instructions: instructions,
        model: model,
        framework: framework,
        code: code,
        timestamp: timestamp
    };
    
    testHistory.unshift(historyItem);
    
    // Keep only last 20 items
    if (testHistory.length > 20) {
        testHistory = testHistory.slice(0, 20);
    }
    
    // Update history display if on history page
    updateHistoryDisplay();
}

function generateTestTitle(instructions) {
    // Generate a short title from instructions
    const words = instructions.split(' ').slice(0, 4);
    return words.join(' ') + (instructions.split(' ').length > 4 ? '...' : '');
}

function updateHistoryDisplay() {
    const container = document.getElementById('history-container');
    if (!container) return;
    
    if (testHistory.length === 0) {
        container.innerHTML = `
            <div class="text-center text-secondary py-5">
                <i class="bi bi-inbox" style="font-size: 3rem;"></i>
                <p class="mt-3">Немате генерирани тестови сеуште</p>
            </div>
        `;
        return;
    }
    
    container.innerHTML = testHistory.map(item => `
        <div class="history-item">
            <div class="d-flex justify-content-between align-items-start">
                <div>
                    <h5>${escapeHtml(item.title)}</h5>
                    <p class="text-secondary mb-2">${escapeHtml(item.instructions.substring(0, 100))}${item.instructions.length > 100 ? '...' : ''}</p>
                    <span class="model-badge ${item.model}">${getModelDisplayName(item.model)}</span>
                    <span class="badge badge-custom">${item.framework === 'selenium' ? 'Selenium' : 'Playwright'}</span>
                </div>
                <div class="text-end">
                    <small class="text-secondary">${item.timestamp}</small>
                    <div class="mt-2">
                        <button class="btn btn-sm copy-btn" onclick="viewHistoryItem(${item.id})">
                            <i class="bi bi-eye"></i> Прегледај
                        </button>
                    </div>
                </div>
            </div>
        </div>
    `).join('');
}

function viewHistoryItem(id) {
    const item = testHistory.find(h => h.id === id);
    if (!item) return;
    
    // Switch to generator page
    showPage('generator');
    
    // Fill in the data
    document.getElementById('test-instructions').value = item.instructions;
    document.getElementById('code-output').innerHTML = `<pre><code class="text-light">${escapeHtml(item.code)}</code></pre>`;
}

function getModelDisplayName(model) {
    const names = {
        'gpt': 'GPT-4',
        'gpt4': 'GPT-4',
        'claude': 'Claude',
        'gemini': 'Gemini'
    };
    return names[model] || model.toUpperCase();
}

// ===================================
// Utility Functions
// ===================================
function escapeHtml(text) {
    const div = document.createElement('div');
    div.textContent = text;
    return div.innerHTML;
}

// ===================================
// Framework Selection Handler
// ===================================
document.addEventListener('DOMContentLoaded', function() {
    // Set up framework radio buttons
    const frameworkRadios = document.querySelectorAll('input[name="framework"]');
    frameworkRadios.forEach(radio => {
        radio.addEventListener('change', function() {
            currentFramework = this.id;
            console.log('Selected framework:', currentFramework);
        });
    });
    
    // Set up navigation links
    document.querySelectorAll('.navbar-nav .nav-link').forEach(link => {
        link.addEventListener('click', function(e) {
            e.preventDefault();
            const href = this.getAttribute('href').substring(1);
            showPage(href);
        });
    });
});

// ===================================
// Export Functions (for future use)
// ===================================
function downloadCode(format) {
    const codeElement = document.querySelector('#code-output pre code');
    if (!codeElement) {
        alert('Нема генериран код за преземање!');
        return;
    }
    
    const code = codeElement.textContent;
    const extension = currentFramework === 'selenium' ? 'py' : 'js';
    const filename = `test_${Date.now()}.${extension}`;
    
    const blob = new Blob([code], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    window.URL.revokeObjectURL(url);
}

// ===================================
// Console Welcome Message
// ===================================
console.log('%c🚀 TestGen AI - Powered by AI', 'color: #6366f1; font-size: 20px; font-weight: bold;');
console.log('%cАвтоматизација на тестови со вештачка интелигенција', 'color: #94a3b8; font-size: 14px;');
console.log('%c© 2026 ФИНКИ - Виктор Крстевски & Ања Брѓовиќ', 'color: #64748b; font-size: 12px;');
